# see travis-ci.org for details

sudo: false

addons:
  apt:
    packages:
      - intltool
      - autoconf
      - automake
      - libtool
      - libgtk-3-dev
      - libglib2.0-dev

language: c

os:
  - linux

compiler:
  - clang
  - gcc

script:
  - sh autogen.sh
  - ./configure
  - make
  - make distcheck
